### ISSUE TITLE
Mismatch between GH Emoji and Slug

### ISSUE THREAD

**Issue by chrisdickinson** [wooorm/remark-slug#1]
Not sure whether this belongs here or [on `remark-validate-links`](https://github.com/wooorm/remark-validate-links), but given the following:

```markdown
### :triangular_ruler: Example
```

GitHub generates `#triangular_ruler-example`. However, `remark-validate-links` expects `#triangularruler-example`, with no underscore, using the following `.remarkrc`:

```json
{
  "plugins": {
    "toc": {
      "tight": true
    },
    "slug": {
      "library": "github"
    },
    "lint": {
      "no-html": false,
      "list-item-spacing": false,
      "list-item-indent": "mixed",
      "code-block-style": "fenced",
      "maximum-heading-length": 80,
      "no-heading-punctuation": false,
      "no-missing-blank-lines": false
    },
    "validate-links": true
  },
  "settings": {
    "listItemIndent": "1",
    "bullet": "*"
  }
}
```

**Comment by wooorm** [comment]
Thanks, @chrisdickinson, for the report. I’m digging in.
