### ISSUE TITLE
Emoji leads to weird slug

### ISSUE THREAD

**Issue by MoOx** [wooorm/remark-slug#2]
![screen shot 2016-08-30 at 12 45 47](https://cloud.githubusercontent.com/assets/157534/18086339/b28e3ad8-6eaf-11e6-9f94-a3b47bc0dcc3.png)

Watch carfully the hovered link (it looks good), but when clicking, I got a weird URL. I assume that the emoji is still here, but hidden.

It seems that remark-slug is ok as you can see in the HTML.

**Comment by wooorm** [comment]
@MoOx What’s making the link?

**Comment by MoOx** [comment]
Oh, I think I posted this in the right place.
Fixed: https://github.com/ben-eb/remark-autolink-headings/issues/30

**Comment by wooorm** [comment]
There’s a `U+FE0F` after the `⚠️`, a “VARIATION SELECTOR-16”, which isn’t stripped. Why’s that there?

**Comment by wooorm** [comment]
Ah, found it, and replied on https://github.com/ben-eb/remark-autolink-headings/issues/30.
