### ISSUE TITLE
Compatibility with remark-react?

### ISSUE THREAD

**Issue by MoOx** [wooorm/remark-slug#8]
Hi!

I am trying to switch from remark-html to remark-react with this:

```js
// remark-plugins.js
import remark from 'remark';
import slug from "remark-slug"
import reactRenderer from 'remark-react';

export default (body: string) => remark()
  .use(slug)

  .use(reactRenderer)

  .processSync(body, {
    commonmark: true,
  })
```

When doing a render I get the following snapshot using jest:

```js
import renderer from 'react-test-renderer';

import remarkPlugins from "../remark-plugins.js"

it("should render markdown as react component", () => {
  const md = remarkPlugins("## Test\n[link](href)").contents
  const tree = renderer.create(md).toJSON();
  expect(tree).toMatchSnapshot();
})
```

```js
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`should render markdown as react component 1`] = `
<div>
  <h2
    id="user-content-test"
  >
    Test
  </h2>
  
  
  <p>
    <a
      href="href"
    >
      link
    </a>
  </p>
</div>
`;
```

As you can see, the "id" is longer than what I would expect. I tried adding `remark-autolink-headings` in the first place: this one is actually adding href around "Test" with the correct slug (#test).
Do you have an idea about this problem and if it can be supported? (Without remark-slug I only get a simple h2, no id attribute.

**Comment by wooorm** [comment]
Yes, that’s possible, but you need to configure how to [sanitize](https://github.com/mapbox/remark-react#configuration) remark react!

**Comment by MoOx** [comment]
Actually my code is going what I found in some docs:

```js
import remark from "remark"
import slug from "remark-slug"
import autoLinkHeadings from "remark-autolink-headings"
import toc from "remark-toc"
import reactRenderer from "remark-react"
import RemarkLowlight from "remark-react-lowlight"
import merge from "deepmerge"
import sanitizeGhSchema from "hast-util-sanitize/lib/github.json"

import languages from "./common-languages.js"

export default (body: string) =>
  remark()
    .use(slug)
    .use(autoLinkHeadings)
    .use(toc)
    .use(reactRenderer, {
      sanitize: merge(sanitizeGhSchema, {
        attributes: { code: ["className"] },
      }),
      remarkReactComponents: {
        code: RemarkLowlight(languages),
      },
    })
    .processSync(body, {
      commonmark: true,
    })
```

Is this good enough?

**Comment by wooorm** [comment]
```js
        attributes: { code: ["className"] },
```

Cool, but that example only allows `className`s on `code` elements!

If you want to allow `id`s on all elements, you need to add a statement, e.g., like this:

```diff
-       attributes: { code: ["className"] },
+       attributes: { code: ["className"], "*": ["id"] },
```

**Comment by MoOx** [comment]
Good to know. I just found how to improve the situation.
`hast-util-sanitize/lib/github.json` have a `clobberPrefix` set to `user-content-`, so I added it empty in my merge like this

```js
    .use(slug)
    .use(reactRenderer, {
      sanitize: merge(
        sanitizeGhSchema,
        {
          // remove user-content from github.json to remark-slug work as expected
          clobberPrefix: "",
          attributes: { code: ["className"] } // here I didn't had to add your trick on id.
        }
      ),
      remarkReactComponents: {
        code: RemarkLowlight(languages),
      },
    })
```

And now that fucking perfect! Thanks a lot for your help and reactivity!

**Comment by wooorm** [comment]
👍

**Comment by yusufameri** [comment]
> Good to know. I just found how to improve the situation.
> `hast-util-sanitize/lib/github.json` have a `clobberPrefix` set to `user-content-`, so I added it empty in my merge like this
> 
> ```js
>     .use(slug)
>     .use(reactRenderer, {
>       sanitize: merge(
>         sanitizeGhSchema,
>         {
>           // remove user-content from github.json to remark-slug work as expected
>           clobberPrefix: "",
>           attributes: { code: ["className"] } // here I didn't had to add your trick on id.
>         }
>       ),
>       remarkReactComponents: {
>         code: RemarkLowlight(languages),
>       },
>     })
> ```
> 
> And now that fucking perfect! Thanks a lot for your help and reactivity!

OMG! This was causing me pain these past few hours. How did you figure out that clobberPrefix existed and/or was doing such a thing? Also on a separate note, I am using typescript with react but can't seem to get any of the typing to appear. Do you know how to do this?

**Comment by wooorm** [comment]
@yusufameri I’m pretty sure Max doesn’t remember how he did that two years ago, but I’m guessing by [reading the docs](https://github.com/remarkjs/remark-react#optionssanitize).
